name: Check Sphinx external links
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 5 * * 0'  # once every Sunday at midnight ET
  workflow_dispatch:

jobs:
  check-external-links:
    name: Check for broken Sphinx external links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0  # tags are required to determine the version

      - name: Set up uv and Python
        uses: astral-sh/setup-uv@v10.2.0
        with:
          python-version: "3.13"

      - name: Install Sphinx dependencies and package
        run: |
          uv sync --upgrade --group docs
          uv pip list

      - name: Check Sphinx external links
        run: |
          cd docs  # run_doc_autogen assumes spec is found in ../spec/
          uv run --no-sync sphinx-build -b linkcheck ./source ./test_build
